CREATE USER IF NOT EXISTS swift IDENTIFIED BY 'base2';

CREATE DATABASE IF NOT EXISTS world;
CREATE DATABASE IF NOT EXISTS homengine;

GRANT ALL PRIVILEGES ON homengine.* TO swift IDENTIFIED BY 'base2';
GRANT SELECT ON world.* TO swift IDENTIFIED BY 'base2';
